apiVersion: v1
kind: Pod
metadata:
  name: chiluk-debug-node2
  labels:
    app: debug
    owner: chiluk
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  containers:
  - image: chiluk/debug
    imagePullPolicy: Always
    name: chiluk-debug
    command:
      - 'sleep'
      - '28800'
  nodeSelector:
    debugdave: "true"
  nodeName: "tst-kexec7.indeed.net"
  tolerations:
  - key: "debugdave"
    operator: "Equal"
    value: "true"
