apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    app: debug
    owner: connor
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  containers:
  - image: clly/debug
    name: debug
    command:
      - 'sleep'
      - '3600'
