apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: chiluk-debug
  labels:
    app: debug
    owner: chiluk
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: debugdave
            operator: "Equal"
            value: "true"
  replicas: 2
  selector:
    matchLabels:
      debugdave: "true"
  template:
    metadata:
      labels:
        debugdave: "true"
    spec:    
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - image: chiluk/debug
        imagePullPolicy: Always
        name: chiluk-debug
        command:
          - 'sleep'
          - '28800'
